import Head from "next/head";
import Footer from "./Footer/Footer";
import Nav from "./Nav"

export default function Layout(props) {
    return (
        <div>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossOrigin="anonymous" referrerpolicy="no-referrer" />
            </Head>
            <Nav />
            <div className="mx-auto max-w-7xl px-4 ">
                {props.children}
            </div>
            <Footer />
        </div>
    )
}
