import Head from 'next/head';
import MainLayout from '../components/Layouts/MainLayout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Andre Jarboe | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </MainLayout>
    </div>
  );
}
